theme: jekyll-theme-cayman

webrick:
  headers:
    My-Header: 问题总结
    My-Other-Header: Java知识

---
layout:     post   				    # 使用的布局（不需要改）
title:      My First Post 				# 标题
subtitle:   Hello World, Hello Blog #副标题
date:       2019-10-25 				# 时间
author:     BY 						# 作者
header-img:      	#这篇文章标题背景图片
catalog: true 						# 是否归档
tags:								#标签
  - 学习
---